In [1]:
import pandas as pd

In [2]:
DATA_PATH = "/home/dark-nik/Desktop/project/data/twcs.csv"
df = pd.read_csv(DATA_PATH)

### Understand the dataset

In [3]:
df.shape

(2811774, 7)

In [4]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                str
 2   inbound                  bool
 3   created_at               str
 4   text                     str
 5   response_tweet_id        str
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 131.4 MB

In [6]:
df.dtypes

tweet_id                     int64
author_id                      str
inbound                       bool
created_at                     str
text                           str
response_tweet_id              str
in_response_to_tweet_id    float64
dtype: object

In [7]:
df.isnull().sum()

tweet_id                         0
author_id                        0
inbound                          0
created_at                       0
text                             0
response_tweet_id          1040629
in_response_to_tweet_id     794335
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

### Find AppleSupport

In [9]:
apple_df = df[df["author_id"] == "AppleSupport"].copy()

In [10]:
apple_df.size

748020

In [11]:
apple_df.count()

tweet_id                   106860
author_id                  106860
inbound                    106860
created_at                 106860
text                       106860
response_tweet_id           31564
in_response_to_tweet_id    106719
dtype: int64

In [12]:
apple_df.shape

(106860, 7)

In [13]:
apple_df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
396,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,697,698.0
398,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,NaN,697.0
401,701,AppleSupport,False,Tue Oct 31 22:26:49 +0000 2017,@115855 Let's go to DM for the next steps. DM ...,NaN,702.0
403,703,AppleSupport,False,Tue Oct 31 22:09:52 +0000 2017,@115855 Any steps tried since it started last ...,702,704.0
405,705,AppleSupport,False,Tue Oct 31 21:57:00 +0000 2017,@115855 That's great it has iOS 11.1 as we can...,"706,704",707.0

### Find the customers

In [14]:
apple_tweet_ids = apple_df["tweet_id"]

#### apple customer replies

In [15]:
customer_replies = df[
    df["in_response_to_tweet_id"].isin(apple_tweet_ids)
].copy()

In [16]:
customer_replies.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
397,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,699,696.0
402,702,115855,True,Tue Oct 31 22:11:31 +0000 2017,@AppleSupport Tried resetting my settings .. r...,701,703.0
404,704,115855,True,Tue Oct 31 21:59:17 +0000 2017,@AppleSupport This is what it looks like https...,703,705.0
406,707,115855,True,Tue Oct 31 21:48:51 +0000 2017,@AppleSupport I️ have an iPhone 7 Plus and yes...,705,708.0
412,713,115856,True,Tue Oct 31 22:35:17 +0000 2017,@AppleSupport Just sent you all my DM,NaN,712.0

In [17]:
tweet_lookup = df.set_index("tweet_id")

In [18]:
tweet_lookup.head()

,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
tweet_id,,,,,,
1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [19]:
tweet_lookup.loc[696]

author_id                                                       AppleSupport
inbound                                                                False
created_at                                    Tue Oct 31 22:27:49 +0000 2017
text                       @115854 We're here for you. Which version of t...
response_tweet_id                                                        697
in_response_to_tweet_id                                                698.0
Name: 696, dtype: object

In [20]:
tweet_lookup.loc[698]["response_tweet_id"]

'696'

In [21]:
def get_next_tweet_id(tweet_id):
    return tweet_lookup.loc[tweet_id, "response_tweet_id"]

In [22]:
get_next_tweet_id(698)

'696'

to chech the things

In [23]:
print(df["tweet_id"].dtype)
print(df["response_tweet_id"].dtype)

int64
str

In [24]:
print(df[df["response_tweet_id"].str.contains(",", na=False)][
    ["tweet_id", "response_tweet_id"]
].head(10))

     tweet_id                                  response_tweet_id
5           6                                                5,7
6           8                                             9,6,10
8          12                                           11,13,14
15         21                                              22,23
60         66                                              64,67
64         71                                              70,72
73         81  80,82,83,84,85,86,87,88,89,90,91,92,93,94,95,9...
78        156                                            155,157
93        172                                            173,171
100       180                                            178,181

In [25]:
def parse_response_ids(value):
    if pd.isna(value):
        return []
    
    return [int(x.strip()) for x in value.split(",")]

test the funcation is working or not

In [26]:
parse_response_ids("11,13,14")
parse_response_ids("697")
parse_response_ids(None)

[]

Apply it to the dataset

In [27]:
df["response_ids"] = df["response_tweet_id"].apply(parse_response_ids)

Check your actual data

In [28]:
df[["tweet_id", "response_tweet_id", "response_ids"]].head(20)

    tweet_id response_tweet_id  response_ids
0          1                 2           [2]
1          2               NaN            []
2          3                 1           [1]
3          4                 3           [3]
4          5                 4           [4]
5          6               5,7        [5, 7]
6          8            9,6,10    [9, 6, 10]
7         11               NaN            []
8         12          11,13,14  [11, 13, 14]
9         15                12          [12]
10        16                15          [15]
11        17                16          [16]
12        18                17          [17]
13        19               NaN            []
14        20                19          [19]
15        21             22,23      [22, 23]
16        22                25          [25]
17        25                26          [26]
18        26                27          [27]
19        27               NaN            []

In [29]:
df[
    df["tweet_id"].isin([5, 6, 7])
][
    [
        "tweet_id",
        "author_id",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
].sort_values("tweet_id")

,tweet_id,author_id,text,response_tweet_id,in_response_to_tweet_id
4,5,115712,@sprintcare I did.,4,6.0
5,6,sprintcare,@115712 Can you please send us a private messa...,"5,7",8.0
2314173,7,115712,@sprintcare the only way I can get a response ...,NaN,6.0

In [30]:
response_map = dict(
    zip(df["tweet_id"], df["response_ids"])
)

In [31]:
response_map[6]

[5, 7]

In [32]:
response_map[8]
response_map[12]

[11, 13, 14]

In [33]:
parent_map = df.set_index("tweet_id")["in_response_to_tweet_id"].to_dict()

In [34]:
parent_map[5]

6.0

In [35]:
df[
    df["tweet_id"].between(1, 8)
][
    [
        "tweet_id",
        "author_id",
        "in_response_to_tweet_id",
        "response_tweet_id",
        "text"
    ]
].sort_values("tweet_id")

,tweet_id,author_id,in_response_to_tweet_id,response_tweet_id,text
0,1,sprintcare,3.0,2,@115712 I understand. I would like to assist y...
1,2,115712,1.0,NaN,@sprintcare and how do you propose we do that
2,3,115712,4.0,1,@sprintcare I have sent several private messag...
3,4,sprintcare,5.0,3,@115712 Please send us a Private Message so th...
4,5,115712,6.0,4,@sprintcare I did.
5,6,sprintcare,8.0,"5,7",@115712 Can you please send us a private messa...
2314173,7,115712,6.0,NaN,@sprintcare the only way I can get a response ...
6,8,115712,NaN,"9,6,10",@sprintcare is the worst customer service

In [36]:
current_id = 6

while pd.notna(current_id):
    print("Tweet:", current_id)
    current_id = parent_map.get(current_id)

Tweet: 6
Tweet: 8.0

In [37]:
parent_map[8]

nan

finding the root of tweet

In [38]:
# Dictionary to store roots that we have already found
# Example: {6: 8, 5: 8, 7: 8}
root_cache = {}

In [39]:
# Dictionary used to remember roots we have already calculated
root_cache = {}


def find_root(tweet_id):
    # If we already know the root, return it immediately
    if tweet_id in root_cache:
        return root_cache[tweet_id]

    # Start from the current tweet
    current_id = tweet_id

    # Keep following the parent until there is no parent
    while pd.notna(current_id):

        # Find the parent of the current tweet
        parent_id = parent_map.get(current_id)

        # If there is no parent, this tweet is the root
        if pd.isna(parent_id):
            root_cache[tweet_id] = current_id
            return current_id

        # Move to the parent tweet
        current_id = int(parent_id)

    # Return None if a root cannot be found
    return None

In [40]:
# Test the optimized root-finding function
print(find_root(5))
print(find_root(6))
print(find_root(7))

# Check what has been stored in the cache
print(root_cache)

8
8
8
{5: 8, 6: 8, 7: 8}

test

In [41]:
# Create a small sample for testing
sample = df.head(20).copy()

# Find the root conversation for every tweet in the sample
sample["root_tweet_id"] = sample["tweet_id"].apply(find_root)

# Display the result
sample[
    [
        "tweet_id",
        "author_id",
        "in_response_to_tweet_id",
        "root_tweet_id"
    ]
]

    tweet_id     author_id  in_response_to_tweet_id  root_tweet_id
0          1    sprintcare                      3.0              8
1          2        115712                      1.0              8
2          3        115712                      4.0              8
3          4    sprintcare                      5.0              8
4          5        115712                      6.0              8
5          6    sprintcare                      8.0              8
6          8        115712                      NaN              8
7         11    sprintcare                     12.0             18
8         12        115713                     15.0             18
9         15    sprintcare                     16.0             18
10        16        115713                     17.0             18
11        17    sprintcare                     18.0             18
12        18        115713                      NaN             18
13        19    sprintcare                     20.0             20
14        20        115715                      NaN             20
15        21  Ask_Spectrum                     24.0             29
16        22        115716                     21.0             29
17        25  Ask_Spectrum                     22.0             29
18        26        115716                     25.0             29
19        27  Ask_Spectrum                     26.0             29

In [42]:
# Calculate the root conversation for every tweet
df["root_tweet_id"] = df["tweet_id"].apply(find_root)

# Check the result
df[
    [
        "tweet_id",
        "in_response_to_tweet_id",
        "root_tweet_id"
    ]
].head(20)

    tweet_id  in_response_to_tweet_id  root_tweet_id
0          1                      3.0              8
1          2                      1.0              8
2          3                      4.0              8
3          4                      5.0              8
4          5                      6.0              8
5          6                      8.0              8
6          8                      NaN              8
7         11                     12.0             18
8         12                     15.0             18
9         15                     16.0             18
10        16                     17.0             18
11        17                     18.0             18
12        18                      NaN             18
13        19                     20.0             20
14        20                      NaN             20
15        21                     24.0             29
16        22                     21.0             29
17        25                     22.0             29
18        26                     25.0             29
19        27                     26.0             29

how many conversations we have

In [43]:
# Count how many different root conversations exist
number_of_conversations = df["root_tweet_id"].nunique()

print("Number of conversations:", number_of_conversations)

Number of conversations: 798012

See the largest conversations

In [67]:
# Count the number of tweets in each conversation
conversation_sizes = (
    df["root_tweet_id"]
    .value_counts()
)

# Display the 20 largest conversations
conversation_sizes.head(20)

root_tweet_id
625855     1390
776752     1060
37012       974
5965        802
88944       661
56184       651
2983023     650
615427      584
278169      551
2390546     534
7442        471
677161      456
5159        448
395394      448
397889      425
82436       402
84404       392
19541       385
132733      385
15807       359
Name: count, dtype: int64

In [69]:
# Select all tweets belonging to conversation 8
conversation_8 = (
    df[df["root_tweet_id"] == 8]
    .sort_values("created_at")
)

# Display the conversation in the order it actually happened
conversation_8[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text",
        "in_response_to_tweet_id",
        "root_tweet_id"
    ]
]

,tweet_id,author_id,inbound,created_at,text,in_response_to_tweet_id,root_tweet_id
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,NaN,8
2314174,10,sprintcare,False,Tue Oct 31 21:45:59 +0000 2017,@115712 Hello! We never like our customers to ...,8.0,8
2314166,9,sprintcare,False,Tue Oct 31 21:46:14 +0000 2017,@115712 I would love the chance to review the ...,8.0,8
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,@115712 Can you please send us a private messa...,8.0,8
2314173,7,115712,True,Tue Oct 31 21:47:48 +0000 2017,@sprintcare the only way I can get a response ...,6.0,8
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,6.0,8
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,5.0,8
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,4.0,8
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,3.0,8
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,1.0,8

Build the conversation function

Find all tweets written by AppleSupport

In [70]:
# Select all tweets written by AppleSupport
apple_df = df[df["author_id"] == "AppleSupport"].copy()

# Check how many AppleSupport tweets we have
print("AppleSupport tweets:", len(apple_df))

AppleSupport tweets: 106860

In [71]:
# Get the root conversation ID for every AppleSupport tweet
apple_roots = apple_df["root_tweet_id"].dropna().unique()

# Check how many different conversations AppleSupport participates in
print("AppleSupport conversations:", len(apple_roots))

AppleSupport conversations: 80702

In [72]:
apple_roots

array([    700,     711,     714, ..., 2987607, 2987663, 2987723],
      shape=(80702,))

Get all tweets belonging to those conversations

In [73]:
# Select all tweets belonging to conversations where AppleSupport participated
apple_conversations = df[
    df["root_tweet_id"].isin(apple_roots)
].copy()

Keep only Customer + AppleSupport

In [74]:
# Keep only customer messages and AppleSupport messages
apple_conversations = apple_conversations[
    (apple_conversations["inbound"] == True) |
    (apple_conversations["author_id"] == "AppleSupport")
].copy()

Sort the conversation chronologically

In [75]:
# Sort messages by conversation and then by the time they were created
apple_conversations = apple_conversations.sort_values(
    ["root_tweet_id", "created_at"]
)

Look at our first AppleSupport conversation

In [76]:
# Get one conversation root for testing
first_root = apple_roots[0]

# Select one AppleSupport conversation
conversation = apple_conversations[
    apple_conversations["root_tweet_id"] == first_root
].copy()

# Display the conversation
conversation[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text",
        "in_response_to_tweet_id",
        "root_tweet_id"
    ]
]

,tweet_id,author_id,inbound,created_at,text,in_response_to_tweet_id,root_tweet_id
400,700,115854,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...,NaN,700
399,698,115854,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB,700.0,700
396,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,698.0,700
397,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,696.0,700
398,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,697.0,700

Give every conversation its own ID

In [77]:
# Use the root tweet as the unique conversation ID
apple_conversations["conversation_id"] = (
    apple_conversations["root_tweet_id"]
)

Check how many AppleSupport conversations we created

In [78]:
# Count the number of unique AppleSupport conversations
print(
    "Total AppleSupport conversations:",
    apple_conversations["conversation_id"].nunique()
)

Total AppleSupport conversations: 80702

In [79]:
# Count total messages in those conversations
print(
    "Total messages:",
    len(apple_conversations)
)

Total messages: 238624

Check the result

In [83]:
# Show the first 30 messages from our AppleSupport dataset
apple_conversations[
    [
        "conversation_id",
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text"
    ]
].head(30)

,conversation_id,tweet_id,author_id,inbound,created_at,text
400,700,700,115854,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...
399,700,698,115854,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB
396,700,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...
397,700,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...
398,700,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...
410,711,711,115855,True,Tue Oct 31 21:29:22 +0000 2017,What is up with this “ I️ “
409,711,710,115855,True,Tue Oct 31 21:29:50 +0000 2017,Why are my I’s question marks ?
408,711,709,115855,True,Tue Oct 31 21:34:45 +0000 2017,@AppleSupport I️ need answers because it’s ann...
407,711,708,AppleSupport,False,Tue Oct 31 21:43:15 +0000 2017,@115855 We'd like to look into this with you. ...
406,711,707,115855,True,Tue Oct 31 21:48:51 +0000 2017,@AppleSupport I️ have an iPhone 7 Plus and yes...
405,711,705,AppleSupport,False,Tue Oct 31 21:57:00 +0000 2017,@115855 That's great it has iOS 11.1 as we can...
2808832,711,706,115855,True,Tue Oct 31 21:58:48 +0000 2017,@AppleSupport Last night
404,711,704,115855,True,Tue Oct 31 21:59:17 +0000 2017,@AppleSupport This is what it looks like https...
403,711,703,AppleSupport,False,Tue Oct 31 22:09:52 +0000 2017,@115855 Any steps tried since it started last ...
402,711,702,115855,True,Tue Oct 31 22:11:31 +0000 2017,@AppleSupport Tried resetting my settings .. r...
401,711,701,AppleSupport,False,Tue Oct 31 22:26:49 +0000 2017,@115855 Let's go to DM for the next steps. DM ...
413,714,714,115856,True,Tue Oct 31 22:19:32 +0000 2017,Hey @AppleSupport and anyone else who upgraded...
411,714,712,AppleSupport,False,Tue Oct 31 22:26:29 +0000 2017,"@115856 Hey, let's work together to figure out..."
412,714,713,115856,True,Tue Oct 31 22:35:17 +0000 2017,@AppleSupport Just sent you all my DM
417,719,719,115857,True,Tue Oct 31 22:01:50 +0000 2017,Tf is wrong with my keyboard @115858
416,719,718,AppleSupport,False,Tue Oct 31 22:05:00 +0000 2017,"@115857 Fill us in on what is happening, then ..."
415,719,717,115857,True,Tue Oct 31 22:13:08 +0000 2017,@AppleSupport This is what is happening... htt...
414,719,716,AppleSupport,False,Tue Oct 31 22:24:54 +0000 2017,@115857 We'd like to investigate further with ...
421,723,723,115859,True,Tue Oct 31 22:11:16 +0000 2017,@115858 @AppleSupport hello are all the lines ...
420,723,722,AppleSupport,False,Tue Oct 31 22:17:30 +0000 2017,@115859 What's going on? We're hapy to help if...
419,723,721,115859,True,Tue Oct 31 22:18:14 +0000 2017,@AppleSupport are the call centres closed for ...
418,723,720,AppleSupport,False,Tue Oct 31 22:24:27 +0000 2017,@115859 We've received your DM and will contin...
427,730,730,115861,True,Tue Oct 31 20:46:35 +0000 2017,"Hello, internet. Can someone explain why this ..."
426,730,729,AppleSupport,False,Tue Oct 31 20:55:34 +0000 2017,@115861 You're in the right place; we'll do al...
425,730,728,115862,True,Tue Oct 31 20:57:26 +0000 2017,@AppleSupport @115861 We’re going to need you ...

Sort Apple conversations correctly

In [84]:
# Sort the Apple conversations by conversation_id
# and then by created_at so messages appear in chronological order

apple_conversations = apple_conversations.sort_values(
    ["conversation_id", "created_at"]
)

# Reset the DataFrame index after sorting
apple_conversations = apple_conversations.reset_index(drop=True)

# Check the result
apple_conversations.head(30)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_ids,root_tweet_id,conversation_id
0,700,115854,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...,698,NaN,[698],700,700
1,698,115854,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB,696,700.0,[696],700,700
2,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,697,698.0,[697],700,700
3,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,699,696.0,[699],700,700
4,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,NaN,697.0,[],700,700
5,711,115855,True,Tue Oct 31 21:29:22 +0000 2017,What is up with this “ I️ “,710,NaN,[710],711,711
6,710,115855,True,Tue Oct 31 21:29:50 +0000 2017,Why are my I’s question marks ?,709,711.0,[709],711,711
7,709,115855,True,Tue Oct 31 21:34:45 +0000 2017,@AppleSupport I️ need answers because it’s ann...,708,710.0,[708],711,711
8,708,AppleSupport,False,Tue Oct 31 21:43:15 +0000 2017,@115855 We'd like to look into this with you. ...,707,709.0,[707],711,711
9,707,115855,True,Tue Oct 31 21:48:51 +0000 2017,@AppleSupport I️ have an iPhone 7 Plus and yes...,705,708.0,[705],711,711
10,705,AppleSupport,False,Tue Oct 31 21:57:00 +0000 2017,@115855 That's great it has iOS 11.1 as we can...,"706,704",707.0,"[706, 704]",711,711
11,706,115855,True,Tue Oct 31 21:58:48 +0000 2017,@AppleSupport Last night,NaN,705.0,[],711,711
12,704,115855,True,Tue Oct 31 21:59:17 +0000 2017,@AppleSupport This is what it looks like https...,703,705.0,[703],711,711
13,703,AppleSupport,False,Tue Oct 31 22:09:52 +0000 2017,@115855 Any steps tried since it started last ...,702,704.0,[702],711,711
14,702,115855,True,Tue Oct 31 22:11:31 +0000 2017,@AppleSupport Tried resetting my settings .. r...,701,703.0,[701],711,711
15,701,AppleSupport,False,Tue Oct 31 22:26:49 +0000 2017,@115855 Let's go to DM for the next steps. DM ...,NaN,702.0,[],711,711
16,714,115856,True,Tue Oct 31 22:19:32 +0000 2017,Hey @AppleSupport and anyone else who upgraded...,"712,715",NaN,"[712, 715]",714,714
17,712,AppleSupport,False,Tue Oct 31 22:26:29 +0000 2017,"@115856 Hey, let's work together to figure out...",713,714.0,[713],714,714
18,713,115856,True,Tue Oct 31 22:35:17 +0000 2017,@AppleSupport Just sent you all my DM,NaN,712.0,[],714,714
19,719,115857,True,Tue Oct 31 22:01:50 +0000 2017,Tf is wrong with my keyboard @115858,718,NaN,[718],719,719
20,718,AppleSupport,False,Tue Oct 31 22:05:00 +0000 2017,"@115857 Fill us in on what is happening, then ...",717,719.0,[717],719,719
21,717,115857,True,Tue Oct 31 22:13:08 +0000 2017,@AppleSupport This is what is happening... htt...,716,718.0,[716],719,719
22,716,AppleSupport,False,Tue Oct 31 22:24:54 +0000 2017,@115857 We'd like to investigate further with ...,NaN,717.0,[],719,719
23,723,115859,True,Tue Oct 31 22:11:16 +0000 2017,@115858 @AppleSupport hello are all the lines ...,722,NaN,[722],723,723
24,722,AppleSupport,False,Tue Oct 31 22:17:30 +0000 2017,@115859 What's going on? We're hapy to help if...,721,723.0,[721],723,723
25,721,115859,True,Tue Oct 31 22:18:14 +0000 2017,@AppleSupport are the call centres closed for ...,720,722.0,[720],723,723
26,720,AppleSupport,False,Tue Oct 31 22:24:27 +0000 2017,@115859 We've received your DM and will contin...,NaN,721.0,[],723,723
27,730,115861,True,Tue Oct 31 20:46:35 +0000 2017,"Hello, internet. Can someone explain why this ...","729,731",NaN,"[729, 731]",730,730
28,729,AppleSupport,False,Tue Oct 31 20:55:34 +0000 2017,@115861 You're in the right place; we'll do al...,728,730.0,[728],730,730
29,728,115862,True,Tue Oct 31 20:57:26 +0000 2017,@AppleSupport @115861 We’re going to need you ...,727,729.0,[727],730,730

Look at one complete Apple conversation

In [85]:
# Select all tweets that belong to conversation 700
conversation_700 = (
    apple_conversations[
        apple_conversations["conversation_id"] == 700
    ]
    .sort_values("created_at")
)

# Display the conversation
conversation_700[
    [
        "conversation_id",
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text"
    ]
]

,conversation_id,tweet_id,author_id,inbound,created_at,text
0,700,700,115854,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...
1,700,698,115854,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB
2,700,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...
3,700,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...
4,700,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...

Check all conversations

In [86]:
# Count how many unique conversations exist
number_of_conversations = apple_conversations["conversation_id"].nunique()

print("Number of conversations:", number_of_conversations)

Number of conversations: 80702

Check several conversations

In [87]:
# Check several Apple conversations automatically
# We will inspect the first 5 conversations in our dataset

sample_conversation_ids = (
    apple_conversations["conversation_id"]
    .dropna()
    .unique()[:5]
)

for conversation_id in sample_conversation_ids:

    # Select all tweets belonging to this conversation
    conversation = (
        apple_conversations[
            apple_conversations["conversation_id"] == conversation_id
        ]
        .sort_values("created_at")
    )

    print("\n" + "=" * 60)
    print(f"Conversation ID: {conversation_id}")
    print(f"Number of tweets: {len(conversation)}")

    # Display the important columns
    display(
        conversation[
            [
                "tweet_id",
                "author_id",
                "created_at",
                "root_tweet_id",
                "conversation_id"
            ]
        ]
    )

============================================================
Conversation ID: 700
Number of tweets: 5

,tweet_id,author_id,created_at,root_tweet_id,conversation_id
0,700,115854,Tue Oct 31 22:16:56 +0000 2017,700,700
1,698,115854,Tue Oct 31 22:17:40 +0000 2017,700,700
2,696,AppleSupport,Tue Oct 31 22:27:49 +0000 2017,700,700
3,697,115854,Tue Oct 31 22:31:23 +0000 2017,700,700
4,699,AppleSupport,Tue Oct 31 22:36:27 +0000 2017,700,700

============================================================
Conversation ID: 711
Number of tweets: 11

,tweet_id,author_id,created_at,root_tweet_id,conversation_id
5,711,115855,Tue Oct 31 21:29:22 +0000 2017,711,711
6,710,115855,Tue Oct 31 21:29:50 +0000 2017,711,711
7,709,115855,Tue Oct 31 21:34:45 +0000 2017,711,711
8,708,AppleSupport,Tue Oct 31 21:43:15 +0000 2017,711,711
9,707,115855,Tue Oct 31 21:48:51 +0000 2017,711,711
10,705,AppleSupport,Tue Oct 31 21:57:00 +0000 2017,711,711
11,706,115855,Tue Oct 31 21:58:48 +0000 2017,711,711
12,704,115855,Tue Oct 31 21:59:17 +0000 2017,711,711
13,703,AppleSupport,Tue Oct 31 22:09:52 +0000 2017,711,711
14,702,115855,Tue Oct 31 22:11:31 +0000 2017,711,711
15,701,AppleSupport,Tue Oct 31 22:26:49 +0000 2017,711,711

============================================================
Conversation ID: 714
Number of tweets: 3

,tweet_id,author_id,created_at,root_tweet_id,conversation_id
16,714,115856,Tue Oct 31 22:19:32 +0000 2017,714,714
17,712,AppleSupport,Tue Oct 31 22:26:29 +0000 2017,714,714
18,713,115856,Tue Oct 31 22:35:17 +0000 2017,714,714

============================================================
Conversation ID: 719
Number of tweets: 4

,tweet_id,author_id,created_at,root_tweet_id,conversation_id
19,719,115857,Tue Oct 31 22:01:50 +0000 2017,719,719
20,718,AppleSupport,Tue Oct 31 22:05:00 +0000 2017,719,719
21,717,115857,Tue Oct 31 22:13:08 +0000 2017,719,719
22,716,AppleSupport,Tue Oct 31 22:24:54 +0000 2017,719,719

============================================================
Conversation ID: 723
Number of tweets: 4

,tweet_id,author_id,created_at,root_tweet_id,conversation_id
23,723,115859,Tue Oct 31 22:11:16 +0000 2017,723,723
24,722,AppleSupport,Tue Oct 31 22:17:30 +0000 2017,723,723
25,721,115859,Tue Oct 31 22:18:14 +0000 2017,723,723
26,720,AppleSupport,Tue Oct 31 22:24:27 +0000 2017,723,723

Check whether the root is consistent

In [88]:
# Check whether each conversation has only ONE root tweet ID

root_check = (
    apple_conversations
    .groupby("conversation_id")["root_tweet_id"]
    .nunique()
)

# Conversations where more than one root was assigned
invalid_conversations = root_check[root_check > 1]

print("Total conversations:", len(root_check))
print("Invalid conversations:", len(invalid_conversations))

if len(invalid_conversations) == 0:
    print("✅ Every conversation has exactly one root tweet.")
else:
    print("❌ Some conversations have multiple root tweets.")
    print(invalid_conversations)

Total conversations: 80702
Invalid conversations: 0
✅ Every conversation has exactly one root tweet.

Check that conversation_id matches root_tweet_id

In [89]:
# For our current design, conversation_id should be the same as root_tweet_id

mismatch = apple_conversations[
    apple_conversations["conversation_id"]
    != apple_conversations["root_tweet_id"]
]

print("Number of mismatched rows:", len(mismatch))

if len(mismatch) == 0:
    print("✅ conversation_id and root_tweet_id match everywhere.")
else:
    print("❌ There are mismatches.")
    display(
        mismatch[
            [
                "tweet_id",
                "root_tweet_id",
                "conversation_id"
            ]
        ].head(20)
    )

Number of mismatched rows: 0
✅ conversation_id and root_tweet_id match everywhere.

Create a clean working copy

In [90]:
# Create a separate copy so that our original dataframe stays unchanged.
# This is important because we may need the original data later.
apple_conversations = apple_conversations.copy()

print("Rows:", len(apple_conversations))
print(
    "Conversations:",
    apple_conversations["conversation_id"].nunique()
)

Rows: 238624
Conversations: 80702

Make sure only Customer + AppleSupport remain

In [91]:
# Keep customer tweets and tweets written by AppleSupport.
# inbound=True represents a customer message.
# author_id="AppleSupport" represents an AppleSupport message.

apple_conversations = apple_conversations[
    (apple_conversations["inbound"] == True) |
    (apple_conversations["author_id"] == "AppleSupport")
].copy()

In [92]:
# Check which authors remain in our dataset.
print(
    apple_conversations["author_id"]
    .value_counts()
    .head(20)
)

author_id
AppleSupport    106860
176402             130
115858              69
144678              54
158590              47
342778              43
203476              35
116333              32
173312              31
229227              28
142826              25
169257              23
510849              23
604238              23
123370              22
287512              22
187675              22
190289              21
190290              20
134128              20
Name: count, dtype: int64

Create a simple speaker column

In [93]:
# Create a human-readable speaker column.
# This converts the technical author information into
# Customer or AppleSupport.

apple_conversations["speaker"] = apple_conversations["author_id"].apply(
    lambda x: "AppleSupport" if x == "AppleSupport" else "Customer"
)

In [94]:
apple_conversations[
    ["tweet_id", "author_id", "speaker", "text"]
].head(20)

,tweet_id,author_id,speaker,text
0,700,115854,Customer,@AppleSupport why are my I️’s changing not sho...
1,698,115854,Customer,@AppleSupport https://t.co/NV0yucs0lB
2,696,AppleSupport,AppleSupport,@115854 We're here for you. Which version of t...
3,697,115854,Customer,@AppleSupport The newest update. I️ made sure ...
4,699,AppleSupport,AppleSupport,@115854 Lets take a closer look into this issu...
5,711,115855,Customer,What is up with this “ I️ “
6,710,115855,Customer,Why are my I’s question marks ?
7,709,115855,Customer,@AppleSupport I️ need answers because it’s ann...
8,708,AppleSupport,AppleSupport,@115855 We'd like to look into this with you. ...
9,707,115855,Customer,@AppleSupport I️ have an iPhone 7 Plus and yes...
10,705,AppleSupport,AppleSupport,@115855 That's great it has iOS 11.1 as we can...
11,706,115855,Customer,@AppleSupport Last night
12,704,115855,Customer,@AppleSupport This is what it looks like https...
13,703,AppleSupport,AppleSupport,@115855 Any steps tried since it started last ...
14,702,115855,Customer,@AppleSupport Tried resetting my settings .. r...
15,701,AppleSupport,AppleSupport,@115855 Let's go to DM for the next steps. DM ...
16,714,115856,Customer,Hey @AppleSupport and anyone else who upgraded...
17,712,AppleSupport,AppleSupport,"@115856 Hey, let's work together to figure out..."
18,713,115856,Customer,@AppleSupport Just sent you all my DM
19,719,115857,Customer,Tf is wrong with my keyboard @115858

Sort the conversations properly

In [95]:
# Sort first by conversation and then by time.
# This gives us the actual chronological conversation flow.

apple_conversations = apple_conversations.sort_values(
    ["conversation_id", "created_at"]
).reset_index(drop=True)

Look at one complete conversation

In [96]:
# Select one complete AppleSupport conversation for inspection.
conversation_700 = apple_conversations[
    apple_conversations["conversation_id"] == 700
].copy()

# Display the conversation in chronological order.
conversation_700[
    [
        "conversation_id",
        "tweet_id",
        "speaker",
        "created_at",
        "text",
        "in_response_to_tweet_id"
    ]
]

,conversation_id,tweet_id,speaker,created_at,text,in_response_to_tweet_id
0,700,700,Customer,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...,NaN
1,700,698,Customer,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB,700.0
2,700,696,AppleSupport,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,698.0
3,700,697,Customer,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,696.0
4,700,699,AppleSupport,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,697.0

Count Customer vs AppleSupport messages

In [97]:
# Count how many messages came from each speaker.
speaker_counts = (
    apple_conversations["speaker"]
    .value_counts()
)

print(speaker_counts)

speaker
Customer        131764
AppleSupport    106860
Name: count, dtype: int64

Count messages per conversation

In [98]:
# Count the number of messages in every conversation.
conversation_sizes = (
    apple_conversations
    .groupby("conversation_id")
    .size()
    .sort_values(ascending=False)
)

# Display the 20 largest conversations.
conversation_sizes.head(20)

conversation_id
612853     282
6658       214
661563     153
937386     125
925552     118
999856     113
307332     113
9200       100
90262       98
1458805     88
2295759     86
208231      79
178654      76
366059      75
61348       74
1703855     69
810319      63
87091       60
1405358     60
1499965     53
dtype: int64

Create the first clean dataset

In [99]:
# Keep only the columns we need for the conversation-analysis dataset.
apple_conversations_clean = apple_conversations[
    [
        "conversation_id",
        "tweet_id",
        "author_id",
        "speaker",
        "inbound",
        "created_at",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
].copy()

In [100]:
# Check the final structure.
apple_conversations_clean.head(20)

,conversation_id,tweet_id,author_id,speaker,inbound,created_at,text,in_response_to_tweet_id,response_tweet_id
0,700,700,115854,Customer,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...,NaN,698
1,700,698,115854,Customer,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB,700.0,696
2,700,696,AppleSupport,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,698.0,697
3,700,697,115854,Customer,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,696.0,699
4,700,699,AppleSupport,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,697.0,NaN
5,711,711,115855,Customer,True,Tue Oct 31 21:29:22 +0000 2017,What is up with this “ I️ “,NaN,710
6,711,710,115855,Customer,True,Tue Oct 31 21:29:50 +0000 2017,Why are my I’s question marks ?,711.0,709
7,711,709,115855,Customer,True,Tue Oct 31 21:34:45 +0000 2017,@AppleSupport I️ need answers because it’s ann...,710.0,708
8,711,708,AppleSupport,AppleSupport,False,Tue Oct 31 21:43:15 +0000 2017,@115855 We'd like to look into this with you. ...,709.0,707
9,711,707,115855,Customer,True,Tue Oct 31 21:48:51 +0000 2017,@AppleSupport I️ have an iPhone 7 Plus and yes...,708.0,705
10,711,705,AppleSupport,AppleSupport,False,Tue Oct 31 21:57:00 +0000 2017,@115855 That's great it has iOS 11.1 as we can...,707.0,"706,704"
11,711,706,115855,Customer,True,Tue Oct 31 21:58:48 +0000 2017,@AppleSupport Last night,705.0,NaN
12,711,704,115855,Customer,True,Tue Oct 31 21:59:17 +0000 2017,@AppleSupport This is what it looks like https...,705.0,703
13,711,703,AppleSupport,AppleSupport,False,Tue Oct 31 22:09:52 +0000 2017,@115855 Any steps tried since it started last ...,704.0,702
14,711,702,115855,Customer,True,Tue Oct 31 22:11:31 +0000 2017,@AppleSupport Tried resetting my settings .. r...,703.0,701
15,711,701,AppleSupport,AppleSupport,False,Tue Oct 31 22:26:49 +0000 2017,@115855 Let's go to DM for the next steps. DM ...,702.0,NaN
16,714,714,115856,Customer,True,Tue Oct 31 22:19:32 +0000 2017,Hey @AppleSupport and anyone else who upgraded...,NaN,"712,715"
17,714,712,AppleSupport,AppleSupport,False,Tue Oct 31 22:26:29 +0000 2017,"@115856 Hey, let's work together to figure out...",714.0,713
18,714,713,115856,Customer,True,Tue Oct 31 22:35:17 +0000 2017,@AppleSupport Just sent you all my DM,712.0,NaN
19,719,719,115857,Customer,True,Tue Oct 31 22:01:50 +0000 2017,Tf is wrong with my keyboard @115858,NaN,718

Check the clean dataset

In [101]:
# Check the shape of the final clean dataset.
# This tells us how many rows and columns we have.

print("Number of rows:", len(apple_conversations_clean))
print("Number of columns:", len(apple_conversations_clean.columns))

# Display all column names.
print("\nColumns:")
print(apple_conversations_clean.columns.tolist())

Number of rows: 238624
Number of columns: 9

Columns:
['conversation_id', 'tweet_id', 'author_id', 'speaker', 'inbound', 'created_at', 'text', 'in_response_to_tweet_id', 'response_tweet_id']

Check missing values

In [102]:
# Check how many missing values exist in each column.
# Missing values are important because they can cause problems
# during later analysis or machine learning.

missing_values = apple_conversations_clean.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
conversation_id                0
tweet_id                       0
author_id                      0
speaker                        0
inbound                        0
created_at                     0
text                           0
in_response_to_tweet_id    80391
response_tweet_id          88765
dtype: int64

Check duplicate tweets

In [103]:
# Check whether the same tweet_id appears more than once.
# Each tweet should normally have a unique tweet_id.

duplicate_tweets = apple_conversations_clean["tweet_id"].duplicated().sum()

print("Number of duplicate tweet IDs:", duplicate_tweets)

Number of duplicate tweet IDs: 0

Save our clean dataset

In [104]:
# Create the output directory if it does not already exist.
from pathlib import Path

output_dir = Path("../output")
output_dir.mkdir(exist_ok=True)

# Save the cleaned AppleSupport conversation dataset as a CSV file.
output_file = output_dir / "apple_conversations_clean.csv"

apple_conversations_clean.to_csv(output_file, index=False)

print(f"Clean dataset saved to: {output_file}")

Clean dataset saved to: ../output/apple_conversations_clean.csv

In [106]:
# Check whether any tweets have empty or whitespace-only text.
# A tweet with no actual text would not be useful for conversation analysis.

empty_text = (
    apple_conversations_clean["text"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print("Number of empty text messages:", empty_text)

Number of empty text messages: 0

In [107]:
# Create a final summary of our cleaned AppleSupport conversation dataset.
# This gives us a quick record of the dataset before we save and push the project.

print("=" * 60)
print("FINAL DATASET SUMMARY")
print("=" * 60)

# Display the total number of tweets.
print(f"Total tweets: {len(apple_conversations_clean):,}")

# Display the total number of conversations.
print(
    f"Total conversations: "
    f"{apple_conversations_clean['conversation_id'].nunique():,}"
)

# Count messages from each speaker.
print("\nMessages by speaker:")
print(apple_conversations_clean["speaker"].value_counts())

# Display the number of columns.
print(f"\nTotal columns: {len(apple_conversations_clean.columns)}")

# Confirm that tweet IDs are unique.
print(
    f"Duplicate tweet IDs: "
    f"{apple_conversations_clean['tweet_id'].duplicated().sum()}"
)

# Confirm that there are no empty messages.
empty_text = (
    apple_conversations_clean["text"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print(f"Empty text messages: {empty_text}")

print("=" * 60)
print("Dataset validation completed successfully.")
print("=" * 60)

============================================================
FINAL DATASET SUMMARY
============================================================
Total tweets: 238,624
Total conversations: 80,702

Messages by speaker:
speaker
Customer        131764
AppleSupport    106860
Name: count, dtype: int64

Total columns: 9
Duplicate tweet IDs: 0
Empty text messages: 0
============================================================
Dataset validation completed successfully.
============================================================